require 'autotest'
require 'autotest/autorun'
require 'autotest/pride'

require_relative './lib/cell'
require_relative './lib/board'
require_relative './lib/ship'
require_relative './lib/gameplay'
require_relative './lib/person'
require_relative './lib/computer'
